### ISSUE TITLE
How to place the particles at init

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#183]

**Comment by awirb** [comment]
maybe intersting to have a look at SW_Workspace.cpp line 2737

**Comment by matthiasto** [comment]
Several options are now available: 
- 1) import particles from SamosAT
- 2) place the particles uniformly in the cell, same mass within one cell (only 1*1, 2*2 ... n*n available)
- 3) same as 2) but  with a random distribution in the subcell
- 4) random distribution within one cell. mass is the same for ALL particles. the number of particles in  a cell is randomly computed so that the total mass is as close to the expected one. A correction factor is applied at thee end to ensure that release mass matches the expected release mass.

**Comment by matthiasto** [comment]
Several options are now available: 
- 1) import particles from SamosAT
- 2) place the particles uniformly in the cell, same mass within one cell (only 1x1, 2x2 ... nxn available)
- 3) same as 2) but  with a random distribution in the subcell
- 4) random distribution within one cell. mass is the same for ALL particles. the number of particles in  a cell is randomly computed so that the total mass is as close to the expected one. A correction factor is applied at thee end to ensure that release mass matches the expected release mass.
