### ISSUE TITLE
Ascii file with NodataValue

### ISSUE THREAD

**Issue by Iceman-bfw** [avaframe/AvaFrame#425]
**Describe the bug**
In:
in2Trans/ascUtils.py
line 88 in readASCdata2numpyArray
rasterdata = np.loadtxt(fname, skiprows=6)

if the .asc file has a NoDataValue it has 7 lines of header and this function will fail due to:
ValueError: could not convert string to float: 'NODATA_value'

**Screenshots**
![grafik](https://user-images.githubusercontent.com/83361439/116435317-83ab7e80-a84b-11eb-85f4-2f7ab5e45956.png)

**Desktop (please complete the following information):**
tried on Windows 10 and on Ubuntu 20

**Comment by fso42** [comment]
Hi Michi, thanks for your bug report. 
What AvaFrame expects atm is the specification from ESRI (basically the de-facto standard), see here:
[Wikipedia Esri](https://en.wikipedia.org/wiki/Esri_grid) and here [ESRI](https://desktop.arcgis.com/en/arcmap/10.3/manage-data/raster-and-images/esri-ascii-raster-format.htm). 

This contains a single mesh dimension information i.e `cellsize` and not `dx` and `dy`. Due to this extra line the reading fails, since we expect exactly 6 header lines according to the specification. 

So as solution, please change your asc files to conform to the specification. 

We will add an error that gives feedback about the problem when reading a wrong header. 

As a sidenote: we are currently handling the llcenter vs llcorner incorrectly (we expect llcenter), but this is being fixed atm (TODO: add issue number)

**Comment by fso42** [comment]
Ok, more info on this:
The command used was: 

`gdal_translate -a_nodata -9999.0 -of AAIGrid INFILE.tif OUTFILE.asc`

From the [gdal documentation](https://gdal.org/drivers/raster/aaigrid.html#raster-aaigrid):

> If pixels being written are not square (the width and height of a pixel in georeferenced units differ) then DX and DY parameters will be output instead of CELLSIZE. Such files can be used in Golden Surfer, but not most other ascii grid reading programs. For force the X pixel size to be used as CELLSIZE use the FORCE_CELLSIZE=YES creation option or resample the input to have square pixels.

So a FORCE_CELLSIZE option is needed to avoid dx and dy

Closing this issue.
