### ISSUE TITLE
Aimec: Find begining of avalanche on polyline

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#50]
With aimec, the original raster is projected on a polyline (avalanche path). We move from x y coordinates to s l coordinates. 
Problem is, for now, if the given polyline starts before the release area, after analysis, the runout length includes the this extra distance between beginning of the line and release area and the s=0 does not correspond to the beginning of the avalanche.
How to choose the s=0 point? start of the rel area, middle? first point at 1kPa? 10?...

**Comment by fso42** [comment]
Do you know how this was handled in th past by JT etc?
Was it required to set it according to the release area?

**Comment by fso42** [comment]
So we have following options (please extend if more):

1. Have 1 fixed line per avalanche, regardless of the release area, starting at the highest possible point of the avalanche


2. Use it relative to release area, i.e. either highest, middle or lowest point

-  what happens if there are more than one?


3. Some pressure/speed/etc related value point

4. ??

**Comment by matthiasto** [comment]
It seems that JTs code starts at the beginning of the poly line

**Comment by fso42** [comment]
Then lets keep this. 
I guess it makes comparisons between different release areas / models easier. 

One just has to remember runout length is not equal to simulation run length...

**Comment by matthiasto** [comment]
Run out measured from the beginning of the run out area point (first point with a slope smaller than a given angle in the .ini file)
In the plots, the start of the s coordinate is the beginning of the aimecPath line.
