### ISSUE TITLE
in-line comments in config files

### ISSUE THREAD

**Issue by snowtechblog** [avaframe/AvaFrame#744]
It's a debate if in-line comments in config files are ok or a nightmare. However, I kinda find them usefull.

Please consider changing line 162, 165, 167, 232, 324 and 380 in in3Utils/cfgUtils.py to
`... = configparser.ConfigParser(inline_comment_prefixes="#")`

and potentially in nearly hundred occurrences in tests_...

**Comment by fso42** [comment]
Hi Anselm, 
Thanks for your suggestion. I fall into the nightmare category and think the potential problems seriously outweigh the (almost nonexistent) benefits. 
The problems are (as stated in the configparser doc):
```
# Inline comments can be harmful because they prevent users
# from using the delimiting characters as parts of values.
```

`Please note that config parsers don’t support escaping of comment prefixes so using inline_comment_prefixes may prevent users from specifying option values with characters used as comment prefixes.`

The only benefit I see is that one can 'block' similar variables a bit more. Because everything you can write in an inline comment can also be put in the line above the variable. 

Or is there something I'm missing?
